import { createContext, useContext, useEffect, useState } from 'react';
import { authApi, gymApi } from '../services/api';
const AuthContext=createContext(null);
const usableName=value=>{const name=String(value||'').trim();return name&&!/@|\d{6,}|_\d{6,}$/.test(name)?name:''};
export function AuthProvider({children}){ const [session,setSession]=useState(()=>{try{return JSON.parse(localStorage.getItem('fitlife_session'))||null}catch{return null}}); const [loading,setLoading]=useState(false);
 const clearSession=()=>{localStorage.removeItem('fitlife_session');setSession(null);};
 const login=async(email,password)=>{setLoading(true);try{const {data}=await authApi.login(email,password);const next={...data,role:String(data.role||'').toUpperCase()};if(!next.token)throw new Error('Incomplete login response.');localStorage.setItem('fitlife_session',JSON.stringify(next));try{const profile=next.role==='MEMBER'?(await gymApi.memberProfile()).data:next.role==='TRAINER'?(await gymApi.trainerProfile()).data:null;const profileName=usableName(profile?.name||profile?.fullName||profile?.displayName);if(profileName)next.displayName=profileName;}catch{}if(!usableName(next.displayName))next.displayName=next.role==='OWNER'?'Owner':next.role==='TRAINER'?'Trainer':next.role==='MEMBER'?'Member':'User';localStorage.setItem('fitlife_session',JSON.stringify(next));setSession(next);return next;}finally{setLoading(false)}};
 const logout=async()=>{try{if(session?.token)await authApi.logout();}catch{}finally{clearSession();}};
 useEffect(()=>{if(session)localStorage.setItem('fitlife_session',JSON.stringify(session))},[session]);
 useEffect(()=>{const onExpired=()=>clearSession();window.addEventListener('fitlife:session-expired',onExpired);return()=>window.removeEventListener('fitlife:session-expired',onExpired)},[]);
 useEffect(()=>{if(!session?.token)return;let active=true;let timer;const validate=async()=>{try{const profile=session.role==='MEMBER'?(await gymApi.memberProfile()).data:session.role==='TRAINER'?(await gymApi.trainerProfile()).data:(await gymApi.dashboard()).data;const profileName=usableName(profile?.name||profile?.fullName||profile?.displayName);if(active&&profileName&&profileName!==session.displayName)setSession(current=>({...current,displayName:profileName}))}catch{}};validate();const expires=Date.parse(session.sessionExpiresAt||'');if(Number.isFinite(expires)){const delay=expires-Date.now();if(delay<=0)clearSession();else timer=window.setTimeout(()=>window.dispatchEvent(new CustomEvent('fitlife:session-expired')),delay)}return()=>{active=false;if(timer)window.clearTimeout(timer)}},[session?.token,session?.role,session?.sessionExpiresAt]); return <AuthContext.Provider value={{session,loading,login,logout}}>{children}</AuthContext.Provider> }
export const useAuth=()=>useContext(AuthContext);
